services:
  - type: web
    name: spotter-hos-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn tripplanner.wsgi:application
    envVars:
      - key: DJANGO_DEBUG
        value: "0"
      - key: DJANGO_ALLOWED_HOSTS
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: DJANGO_SECRET_KEY
        generateValue: true
